AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda for S3 → RDS ingestion

Parameters:
  S3BucketName:
    Type: String

  PgHost:
    Type: String

  PgDatabase:
    Type: String
    Default: chatbot

  PgUser:
    Type: String
    Default: postgres

  PgPassword:
    Type: String
    NoEcho: true
