AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda for S3 → RDS ingestion

Parameters:
  S3BucketName:
    Type: String

  PgHost:
    Type: String

  PgDatabase:
    Type: String
    Default: chatbot

  PgUser:
    Type: String
    Default: postgres

  PgPassword:
    Type: String
    NoEcho: true

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: chatbot-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: S3ReadPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"


  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref S3IngestionLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${S3BucketName}"

Outputs:
  LambdaArn:
    Value: !GetAtt S3IngestionLambda.Arn